import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

// The rules that keep this codebase consistent, written as tests. They are described in
// AGENTS.md and guides/ARCHITECTURE.md. If one fails, the message says which file broke which rule.

const root = process.cwd();
const read = (path: string) => readFileSync(join(root, path), "utf8");

/** All files under `dir` (relative to the repo root) matching `ext`, skipping generated code. */
function filesIn(dir: string, ext: RegExp): string[] {
  const absolute = join(root, dir);
  if (!existsSync(absolute)) return [];
  return readdirSync(absolute).flatMap((name) => {
    const path = join(dir, name);
    if (statSync(join(root, path)).isDirectory()) return filesIn(path, ext);
    return ext.test(name) ? [path] : [];
  });
}

// `src/components/ui` is generated shadcn code, `routeTree.gen.ts` is generated by the router.
const handWrittenComponents = filesIn("src/components", /\.tsx?$/).filter(
  (f) => !f.startsWith(join("src", "components", "ui")),
);
const pageFiles = [...handWrittenComponents, "src/routes/index.tsx"];

/** Module specifiers a file imports from, ignoring anything that only appears in comments. */
const importsOf = (file: string) => {
  const code = read(file)
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/^\s*\/\/.*$/gm, "");
  return [...code.matchAll(/from\s+["']([^"']+)["']/g)].map((m) => m[1] ?? "");
};

describe("design system", () => {
  it("uses colour tokens, never raw colours, in components and pages", () => {
    const raw = /#[0-9a-fA-F]{3,8}\b|\b(?:rgb|rgba|hsl|hsla|oklch|lab|lch)\(/;
    for (const file of pageFiles) {
      const hit = read(file).match(raw);
      expect(
        hit,
        `${file} hard-codes a colour (${hit?.[0]}). Use a token from styles/tokens.css.`,
      ).toBeNull();
    }
  });

  it("loads fonts from this site, not from a third-party host", () => {
    for (const file of [...filesIn("src", /\.(tsx?|css)$/)]) {
      expect(read(file), file).not.toMatch(/fonts\.(googleapis|gstatic)\.com/);
    }
  });

  it("imports every stylesheet in src/styles from src/styles.css", () => {
    const entry = read("src/styles.css");
    for (const file of filesIn("src/styles", /\.css$/)) {
      expect(entry, `${file} is not imported by src/styles.css`).toContain(
        `./styles/${file.split(/[\\/]/).pop()}`,
      );
    }
  });
});

describe("architecture", () => {
  it("keeps content in src/data: data files import nothing from the app", () => {
    for (const file of filesIn("src/data", /\.ts$/)) {
      for (const source of importsOf(file)) {
        expect(
          source.startsWith("."),
          `${file} imports "${source}". Data must stay self-contained.`,
        ).toBe(true);
      }
    }
  });

  it("keeps components independent of routes", () => {
    for (const file of handWrittenComponents) {
      for (const source of importsOf(file)) {
        expect(source, `${file} imports a route`).not.toMatch(/^@\/routes|\/routes\//);
      }
    }
  });

  it("keeps the route file thin: it wires the URL to the page and nothing more", () => {
    const lines = read("src/routes/index.tsx").trimEnd().split("\n").length;
    expect(
      lines,
      "src/routes/index.tsx is getting long. Build the page in src/components instead.",
    ).toBeLessThanOrEqual(40);
  });

  it("keeps components small and single-purpose", () => {
    for (const file of handWrittenComponents) {
      const lines = read(file).trimEnd().split("\n").length;
      expect(
        lines,
        `${file} is ${lines} lines. Split it into smaller components.`,
      ).toBeLessThanOrEqual(200);
    }
  });

  it("builds every page section from the shared Container", () => {
    for (const file of filesIn("src/components/sections", /\.tsx$/)) {
      expect(read(file), `${file} should wrap its content in <Container>`).toContain("<Container");
    }
  });

  it("puts every section component on the home page", () => {
    const home = read("src/components/HomePage.tsx");
    for (const file of filesIn("src/components/sections", /\.tsx$/)) {
      const name = file.split(/[\\/]/).pop()?.replace(".tsx", "") ?? "";
      expect(home, `${name} is not used by HomePage`).toContain(`<${name}`);
    }
  });
});

describe("project setup", () => {
  const pkg = JSON.parse(read("package.json")) as { scripts: Record<string, string> };

  it("keeps the build and check scripts the deploy relies on", () => {
    for (const script of [
      "build",
      "build:static",
      "verify:static",
      "check",
      "lint",
      "test",
      "typecheck",
    ]) {
      expect(pkg.scripts[script], `package.json is missing the "${script}" script`).toBeTruthy();
    }
  });

  it("keeps the static export and verification scripts", () => {
    for (const file of ["scripts/export-static.mjs", "scripts/verify-static.mjs"]) {
      expect(existsSync(join(root, file)), file).toBe(true);
    }
  });

  it("keeps the workflow that publishes the site automatically", () => {
    const workflow = ".github/workflows/publish.yml";
    expect(existsSync(join(root, workflow)), `${workflow} was removed`).toBe(true);
    expect(read(workflow), "the workflow must run the full check before publishing").toContain(
      "bun run check",
    );
  });

  it("keeps the written rules that guide future edits", () => {
    const agents = read("AGENTS.md");
    expect(agents).toContain("LOVABLE:BEGIN");
    expect(agents).toContain("Project conventions");
    for (const doc of ["guides/ARCHITECTURE.md", "guides/DESIGN_SYSTEM.md"]) {
      expect(existsSync(join(root, doc)), doc).toBe(true);
      expect(agents, `AGENTS.md should point to ${doc}`).toContain(doc);
    }
  });

  it("keeps the published site in docs/ (the folder GitHub Pages serves)", () => {
    for (const file of ["docs/index.html", "docs/404.html", "docs/.nojekyll"]) {
      expect(
        existsSync(join(root, file)),
        `${file} is missing. Run "bun run build:static" and commit docs/.`,
      ).toBe(true);
    }
  });

  it("ships the files link previews and search engines need", () => {
    for (const file of [
      "public/og.jpg",
      "public/sitemap.xml",
      "public/robots.txt",
      "public/favicon.ico",
    ]) {
      expect(existsSync(join(root, file)), file).toBe(true);
    }
    expect(read("public/robots.txt")).toContain("Sitemap:");
  });
});
